[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[service]
name = "baby-name-service"
port = 3001

[[plugins]]
name = "Redis"
envs = ["REDIS_URL"] 